[settings]
max_content_size = 900

[telemetry]
level = "debug"
enable_remote_otlp = true
otlp_address = "http://localhost:4317"

[server.http]
address = "0.0.0.0:2892"

[storage.opensearch]
address = "http://localhost:9200"
username = "admin"
password = "admin"

[storage.opensearch.cluster]
number_of_shards = 1
number_of_replicas = 1

[storage.opensearch.semantic]
model_id = "uPRh30JcBW8Qg3Gf4I6K"
knn_ef_searcher = 100
knn_dimension = 768
token_limit = 700
overlap_rate = 0.2

[cache]
is_enabled = false

[cache.redis]
address = "redis://localhost:6379"
username = "redis"
password = "redis"
expired = 3600
