[settings]
mac_content_size = 90000

[otlp]
enable_remote_otlp = true

[otlp.logger]
level = "debug"
address = "http://loki:3100"

[otlp.tracing]
address = "http://jaeger:4317"

[server.http]
address = "0.0.0.0:2892"

[storage.opensearch]
address = "http://opensearch:9200"
username = "admin"
password = "admin"

[storage.opensearch.cluster]
number_of_shards = 1
number_of_replicas = 1

[storage.opensearch.semantic]
model_id = "uPRh30JcBW8Qg3Gf4I6K"
knn_ef_searcher = 100
knn_dimension = 768
token_limit = 700
overlap_rate = 0.2

[cache]
is_enabled = false

[cache.redis]
address = "redis://redis:6379"
username = "redis"
password = "redis"
expired = 3600
